### ISSUE TITLE
Add Support for cognitivecomputations/dolphin-phi-2-kensho and other models that are configured like it which follow Meta's paper "MobileLLM: Optimizing Sub-billion Parameter Language Models for On-Device Use Cases" (https://arxiv.org/abs/2402.14905)

### ISSUE THREAD

**Issue by joseph777111** [ggerganov/llama.cpp#6333]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Add a new model architecture that follows Meta's paper "MobileLLM: Optimizing Sub-billion Parameter Language Models for On-Device Use Cases" to enable smaller models, which are configured like [cognitivecomputations/dolphin-phi-2-kensho](https://huggingface.co/cognitivecomputations/dolphin-phi-2-kensho) to be more intelligent. 

<b>This is a hack around pytorch + huggingface Transformers library to make the original Dolphin Phi-2 to behave in a way inspired by the Meta's paper "MobileLLM: Optimizing Sub-billion Parameter Language Models for On-Device Use Cases" [https://arxiv.org/abs/2402.14905]

By Fernando, Eric and David

One of the key ideas is that it works as if it was like "an online passthrough", by applying a loop on a module SuperClass, that groups layers, in a such way they get their forward method repeated in a loop. So, in theory, you can observe more intelligence in the same way MegaDolphin 120b, Professor 155b, Venus120b and other huge models, but use way less vRAM, because instead of cloning the weights, we share them in the vRAM.

And actually, this concept could be also used to enable the training of way more efficient models.

We hope the community enjoy it and make good use of it.

It won't work out of the box in the other models. Their "modeling files" should be changed accordingly to achieve the same effect. </b>
# Motivation

Better, more intelligent models for less vRAM.

# Possible Implementation
[Meta's paper "MobileLLM: Optimizing Sub-billion Parameter Language Models for On-Device Use Cases"]( https://arxiv.org/abs/2402.14905)
https://huggingface.co/cognitivecomputations/dolphin-phi-2-kensho implements ideas from the aforementioned paper in their model.
