### ISSUE TITLE
Tracking: LoRA

### ISSUE THREAD

**Issue by jon-chuang** [ggerganov/llama.cpp#964]
Here are some outstanding issues for LoRA:
- [x] Base implementation (https://github.com/ggerganov/llama.cpp/pull/820)
- [ ] Improve LoRA application time with SIMD (AVX, AVX2) (https://github.com/ggerganov/llama.cpp/issues/956)
- [ ] Improve LoRA loading time with MMAP on base model
   - [ ] quantizing an MMAPed float16 base model that has had LoRA applied
- [ ] Interpolation of weights (start with 1, look into multiple) (https://github.com/ggerganov/llama.cpp/issues/905)
- [ ] Export loaded model to binfile (standalone in CLI with LoRA (`--export-lora` flag); interactively (?)) (https://github.com/ggerganov/llama.cpp/issues/904)
- [ ] Investigate extracting LoRA for arbitrary models  (see [PEFT issue](https://github.com/huggingface/peft/issues/312))

**Comment by captainzero93** [comment]
really desperate to start uing LoRA, however I use GPTQ-4bit-32g.GGML   will this be a problem?

**Comment by jon-chuang** [comment]
So far, we've seen issues with quality on 4 bit. That being said, it has produced reasonable output for me _some_ of the time. It is still under investigation.

**Comment by bmanturner** [comment]
Would this be a good place to request support for multiple lora adapters sharing a similar base model? See here for inspiration: https://github.com/lm-sys/FastChat/pull/1905

**Comment by Green-Sky** [comment]
> Improve LoRA loading time with MMAP on base model 

was done here https://github.com/ggerganov/llama.cpp/pull/2095

also not sure this issue is the right one
